"""initial persistence schema

Revision ID: c3d9092785c3
Revises: 
Create Date: 2026-08-12 01:04:43.778255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3d9092785c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('requires_vision_pages', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('image_content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('requires_vision', sa.Boolean(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages'))
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('depth', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_used', sa.String(length=100), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synthesis', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('total_source_count', sa.Integer(), nullable=False),
    sa.Column('total_evidence_count', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_investigations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index(op.f('ix_investigations_created_at'), 'investigations', ['created_at'], unique=False)
    op.create_index(op.f('ix_investigations_user_id'), 'investigations', ['user_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=True),
    sa.Column('sub_question_id', sa.String(length=32), nullable=False),
    sa.Column('has_supporting_and_contradicting_evidence', sa.Boolean(), nullable=False),
    sa.Column('unresolved_conflicts', sa.JSON(), nullable=False),
    sa.Column('conflicting_source_claims', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_conflicts_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflicts')),
    sa.UniqueConstraint('investigation_id', 'sub_question_id', name='uq_conflicts_investigation_id_sub_question_id')
    )
    op.create_index(op.f('ix_conflicts_investigation_id'), 'conflicts', ['investigation_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('sub_question_id', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('retrieval_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('relevant_passage', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_evidence_items_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items')),
    sa.UniqueConstraint('investigation_id', 'evidence_id', name='uq_evidence_items_investigation_id_evidence_id')
    )
    op.create_index(op.f('ix_evidence_items_investigation_id'), 'evidence_items', ['investigation_id'], unique=False)
    op.create_table('investigation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('overall_evidence_picture', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('confidence_rationale', sa.Text(), nullable=False),
    sa.Column('strongest_supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('strongest_contradicting_evidence', sa.JSON(), nullable=True),
    sa.Column('unresolved_conflicts', sa.JSON(), nullable=False),
    sa.Column('important_limitations', sa.JSON(), nullable=False),
    sa.Column('alternative_explanations', sa.JSON(), nullable=False),
    sa.Column('evidence_gaps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_reports_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_reports')),
    sa.UniqueConstraint('investigation_id', name='uq_investigation_reports_investigation_id')
    )
    op.create_index(op.f('ix_investigation_reports_investigation_id'), 'investigation_reports', ['investigation_id'], unique=False)
    op.create_table('investigation_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=32), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_used', sa.String(length=100), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('input_references', sa.JSON(), nullable=False),
    sa.Column('output_references', sa.JSON(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_steps_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_steps')),
    sa.UniqueConstraint('investigation_id', 'step_id', name='uq_investigation_steps_investigation_id_step_id')
    )
    op.create_index(op.f('ix_investigation_steps_investigation_id'), 'investigation_steps', ['investigation_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('credibility', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_sources_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('investigation_id', 'source_id', name='uq_sources_investigation_id_source_id')
    )
    op.create_index(op.f('ix_sources_investigation_id'), 'sources', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_investigation_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_investigation_steps_investigation_id'), table_name='investigation_steps')
    op.drop_table('investigation_steps')
    op.drop_index(op.f('ix_investigation_reports_investigation_id'), table_name='investigation_reports')
    op.drop_table('investigation_reports')
    op.drop_index(op.f('ix_evidence_items_investigation_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_conflicts_investigation_id'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_investigations_user_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_created_at'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
