"""Report generators that synthesize document-grounded investigations."""

import asyncio
import json
from abc import ABC, abstractmethod
from typing import Any

from pydantic import ValidationError

from app.core.exceptions import ApplicationConfigurationError
from app.schemas.documents import (
    DocumentExcerpt,
    DocumentInvestigationReport,
    DocumentUsedRef,
)
from app.schemas.investigation import InvestigationPlan


class DocumentReportContext:
    """All document-grounded material handed to a report generator."""

    def __init__(
        self,
        *,
        query: str,
        plan: InvestigationPlan,
        excerpts: list[DocumentExcerpt],
        documents_used: list[DocumentUsedRef],
        graph_notes: list[str],
    ) -> None:
        self.query = query
        self.plan = plan
        self.excerpts = excerpts
        self.documents_used = documents_used
        self.graph_notes = graph_notes


class DocumentReportGeneratorError(Exception):
    """Base error for report generation failures."""


class DocumentReportGenerator(ABC):
    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Return the stable generator identifier."""

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Return the configured model identifier."""

    @abstractmethod
    async def generate(
        self,
        context: DocumentReportContext,
    ) -> dict[str, Any]:
        """Return a JSON-compatible document investigation report."""

    async def aclose(self) -> None:
        """Release provider resources when the adapter owns any."""


class MockDocumentReportGenerator(DocumentReportGenerator):
    """Deterministic fallback that extracts findings from the excerpts."""

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def model_name(self) -> str:
        return "mock-document-investigator"

    async def generate(
        self,
        context: DocumentReportContext,
    ) -> dict[str, Any]:
        findings: list[str] = []
        for excerpt in context.excerpts[:5]:
            findings.append(
                f"{excerpt.filename} (page {excerpt.page_number}): "
                f"{excerpt.text[:160]}"
            )
        if not findings:
            findings = [
                "The stored documents do not contain extractable text for "
                "this query."
            ]
        return DocumentInvestigationReport(
            status="completed",
            query=context.query,
            depth=context.plan.depth,
            category=context.plan.category,
            findings=findings,
            supporting_excerpts=context.excerpts[:5],
            contradicted_claims=[
                note for note in context.graph_notes if "contradict" in note
            ],
            limitations=["Report generated by the deterministic mock generator."],
            recommendations=[
                "Enable a configured LLM provider for deeper document analysis."
            ],
            documents_used=context.documents_used,
            provider_used=self.provider_name,
            model_used=self.model_name,
            fallback_used=True,
        ).model_dump(mode="json")


REPORT_SYSTEM_INSTRUCTION = (
    "You are an investigative analyst. Ground every finding strictly in the "
    "provided document excerpts. Return JSON matching the schema below. "
    "Quote excerpts verbatim; never invent facts that are absent from the "
    "excerpts."
)


class GeminiDocumentReportGenerator(DocumentReportGenerator):
    """Google Gemini adapter for document-grounded investigations."""

    def __init__(
        self,
        *,
        model_name: str,
        api_key: str | None,
        timeout_seconds: int = 60,
        client: Any | None = None,
    ) -> None:
        from google import genai
        from google.genai import errors as genai_errors

        normalized_model = model_name.strip()
        if not normalized_model:
            raise ApplicationConfigurationError(
                "LLM_MODEL is required when LLM_PROVIDER is 'gemini'."
            )
        normalized_api_key = (api_key or "").strip()
        if not normalized_api_key:
            raise ApplicationConfigurationError(
                "GEMINI_API_KEY is required when LLM_PROVIDER is 'gemini'."
            )
        if timeout_seconds <= 0:
            raise ApplicationConfigurationError(
                "LLM_TIMEOUT_SECONDS must be greater than zero."
            )

        self._genai = genai
        self._genai_errors = genai_errors
        self._model_name = normalized_model
        self._timeout_seconds = timeout_seconds
        self._api_key_for_redaction = normalized_api_key
        self._owns_client = client is None
        self._client = client or genai.Client(api_key=normalized_api_key)

    @property
    def provider_name(self) -> str:
        return "gemini"

    @property
    def model_name(self) -> str:
        return self._model_name

    async def generate(
        self,
        context: DocumentReportContext,
    ) -> dict[str, Any]:
        from google.genai import types

        prompt = self._build_prompt(context)
        config = types.GenerateContentConfig(
            response_mime_type="application/json",
            response_json_schema=DocumentInvestigationReport.model_json_schema(),
            temperature=0.0,
            system_instruction=REPORT_SYSTEM_INSTRUCTION,
        )
        try:
            response = await asyncio.wait_for(
                self._client.aio.models.generate_content(
                    model=self._model_name,
                    contents=prompt,
                    config=config,
                ),
                timeout=self._timeout_seconds,
            )
            response_text = response.text
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            raise DocumentReportGeneratorError(
                f"Gemini report generation failed ({type(exc).__name__})."
            ) from exc

        if not isinstance(response_text, str) or not response_text.strip():
            raise DocumentReportGeneratorError(
                "Gemini report generation returned an empty response."
            )
        try:
            payload = json.loads(response_text)
            return DocumentInvestigationReport.model_validate(payload).model_dump(
                mode="json"
            )
        except (json.JSONDecodeError, ValidationError) as exc:
            raise DocumentReportGeneratorError(
                "Gemini report output failed schema validation."
            ) from exc

    @staticmethod
    def _build_prompt(context: DocumentReportContext) -> str:
        parts: list[str] = [
            f"Investigation query: {context.query}",
            (
                "Investigation plan: "
                + "; ".join(
                    f"{sq.id} {sq.question}" for sq in context.plan.sub_questions
                )
            ),
        ]
        if context.excerpts:
            excerpt_blocks = "\n\n".join(
                f"[{excerpt.filename}, page {excerpt.page_number}]\n"
                f"{excerpt.text}"
                for excerpt in context.excerpts
            )
            parts.append(f"Document excerpts:\n{excerpt_blocks}")
        else:
            parts.append("Document excerpts: (none available)")
        if context.graph_notes:
            parts.append(
                "Graph-derived notes:\n" + "\n".join(context.graph_notes)
            )
        parts.append(
            "Respond with a JSON object of type "
            "DocumentInvestigationReport."
        )
        return "\n\n".join(parts)

    async def aclose(self) -> None:
        if self._owns_client:
            await self._client.aio.aclose()


__all__ = [
    "DocumentReportContext",
    "DocumentReportGenerator",
    "DocumentReportGeneratorError",
    "GeminiDocumentReportGenerator",
    "MockDocumentReportGenerator",
]
